import datetime
import copy

# Purchasing
PURCHASE_PRICE = 700000
DOWNPAYMENT = 300000
LOAN_AMOUNT = PURCHASE_PRICE - DOWNPAYMENT

INTEREST_RATE = .08
MORTGAGE_CHOICE = 'sac'
SELLING_COST = .06
CONTRACT_DATE = datetime.date(2019, 9, 1)

# Borrowers' age (mutuários)
BIRTH1 = datetime.date(1968, 9, 23)
BIRTH2 = datetime.date(1970, 9, 1)

PERC_BORROWER1 = .5
PERC_BORROWER2 = 1 - PERC_BORROWER1

# Macroeconomics
INFLATION = .04
RETURN_ON_CASH = .06

# Rental
RENT_PERCENTAGE = .0035
RENT_RAISING_PERIOD = 12

AMORTIZATION_MONTHS = 120

TAX = .15
CUSTODY_FEE = .0003

REAL_RETURN = round((RETURN_ON_CASH - INFLATION) * (1 - TAX), 4)

DATA = 'data.csv'
