import datetime

# Purchasing
PURCHASE_PRICE = 800000
DOWNPAYMENT = 240000
LOAN_AMOUNT = PURCHASE_PRICE - DOWNPAYMENT
HOUSE_APPRECIATION = .0

INTEREST_RATE = .09
MORTGAGE_CHOICE = 'sac'
SELLING_COST = .06
CONTRACT_DATE = datetime.date(2019, 9, 17)

# Borrowers' age (mutuários)
BIRTH1 = datetime.date(1969, 9, 23)
BIRTH2 = datetime.date(1970, 9, 1)

PERC_BORROWER1 = .5
PERC_BORROWER2 = 1 - PERC_BORROWER1

# Macroeconomics
INFLATION = .04
RETURN_ON_CASH = .05

# Rental -- about 3.5% of home value per year
RENT_PERCENTAGE = .035 / 12
RENT_RAISING_PERIOD = 12

AMORTIZATION_MONTHS = 360

TAX = .15
CUSTODY_FEE = .0003

# REAL
REAL_RETURN = round((RETURN_ON_CASH - INFLATION) * (1 - TAX), 6)
HOUSE_REAL_APPRECIATION = round((HOUSE_APPRECIATION - INFLATION) * (1 - TAX), 6)

DATA = 'data.csv'
